"""initial

Revision ID: b6e9b9855331
Revises:
Create Date: 2026-09-19 20:06:54.844349

"""

from __future__ import annotations

import sqlalchemy as sa
from alembic import op

revision = "0001"
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "creators",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("campaign_id", sa.String(length=32), nullable=False),
        sa.Column("vanity", sa.String(length=255), nullable=True),
        sa.Column("name", sa.String(length=255), nullable=False),
        sa.Column("url", sa.String(length=1024), nullable=True),
        sa.Column("creator_user_id", sa.String(length=32), nullable=True),
        sa.Column("creation_name", sa.String(length=255), nullable=True),
        sa.Column("avatar_url", sa.String(length=2048), nullable=True),
        sa.Column("cover_url", sa.String(length=2048), nullable=True),
        sa.Column("is_nsfw", sa.Boolean(), nullable=True),
        sa.Column("monitored", sa.Boolean(), nullable=False),
        sa.Column("auto_download", sa.Boolean(), nullable=False),
        sa.Column("include_images", sa.Boolean(), nullable=False),
        sa.Column("include_audio", sa.Boolean(), nullable=False),
        sa.Column("include_attachments", sa.Boolean(), nullable=False),
        sa.Column("download_since", sa.DateTime(), nullable=True),
        sa.Column("folder_name", sa.String(length=255), nullable=True),
        sa.Column("last_scan_at", sa.DateTime(), nullable=True),
        sa.Column("last_full_scan_at", sa.DateTime(), nullable=True),
        sa.Column("last_scan_status", sa.String(length=16), nullable=True),
        sa.Column("last_scan_error", sa.Text(), nullable=True),
        sa.Column("pledge_active", sa.Boolean(), nullable=True),
        sa.Column("pledge_checked_at", sa.DateTime(), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_table(
        "settings",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "system_state",
        sa.Column("key", sa.String(length=64), nullable=False),
        sa.Column("value", sa.JSON(), nullable=True),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.PrimaryKeyConstraint("key"),
    )
    op.create_table(
        "posts",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.String(length=32), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=1024), nullable=False),
        sa.Column("content_html", sa.Text(), nullable=True),
        sa.Column("teaser_text", sa.Text(), nullable=True),
        sa.Column("post_type", sa.String(length=64), nullable=True),
        sa.Column("url", sa.String(length=2048), nullable=True),
        sa.Column("published_at", sa.DateTime(), nullable=True),
        sa.Column("edited_at", sa.DateTime(), nullable=True),
        sa.Column("current_user_can_view", sa.Boolean(), nullable=False),
        sa.Column("thumbnail_url", sa.String(length=2048), nullable=True),
        sa.Column("embed_provider", sa.String(length=64), nullable=True),
        sa.Column("embed_url", sa.String(length=2048), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("folder_path", sa.String(length=2048), nullable=True),
        sa.Column("raw_json", sa.JSON(), nullable=True),
        sa.Column("first_seen_at", sa.DateTime(), nullable=False),
        sa.Column("last_seen_at", sa.DateTime(), nullable=False),
        sa.Column("urls_fetched_at", sa.DateTime(), nullable=True),
        sa.Column("sidecars_written", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["creator_id"], ["creators.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_posts_creator_id"), ["creator_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_posts_post_id"), ["post_id"], unique=False)
        batch_op.create_index(
            "ix_posts_creator_published", ["creator_id", "published_at"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_posts_published_at"), ["published_at"], unique=False)
        batch_op.create_index(batch_op.f("ix_posts_status"), ["status"], unique=False)

    op.create_table(
        "scan_runs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("mode", sa.String(length=16), nullable=False),
        sa.Column("trigger", sa.String(length=16), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("started_at", sa.DateTime(), nullable=False),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("pages_fetched", sa.Integer(), nullable=False),
        sa.Column("posts_seen", sa.Integer(), nullable=False),
        sa.Column("posts_new", sa.Integer(), nullable=False),
        sa.Column("posts_updated", sa.Integer(), nullable=False),
        sa.Column("media_queued", sa.Integer(), nullable=False),
        sa.Column("error", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["creator_id"], ["creators.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("scan_runs", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_scan_runs_creator_id"), ["creator_id"], unique=False)

    op.create_table(
        "media_items",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("media_key", sa.String(length=128), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("source", sa.String(length=32), nullable=False),
        sa.Column("source_url", sa.Text(), nullable=True),
        sa.Column("remote_file_name", sa.String(length=1024), nullable=True),
        sa.Column("mimetype", sa.String(length=128), nullable=True),
        sa.Column("remote_size_bytes", sa.Integer(), nullable=True),
        sa.Column("remote_metadata", sa.JSON(), nullable=True),
        sa.Column("status", sa.String(length=32), nullable=False),
        sa.Column("status_reason", sa.Text(), nullable=True),
        sa.Column("wanted", sa.Boolean(), nullable=False),
        sa.Column("attempts", sa.Integer(), nullable=False),
        sa.Column("next_retry_at", sa.DateTime(), nullable=True),
        sa.Column("last_error", sa.Text(), nullable=True),
        sa.Column("file_path", sa.String(length=2048), nullable=True),
        sa.Column("file_size_bytes", sa.Integer(), nullable=True),
        sa.Column("sha256", sa.String(length=64), nullable=True),
        sa.Column("completed_at", sa.DateTime(), nullable=True),
        sa.Column("order_index", sa.Integer(), nullable=False),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["creator_id"], ["creators.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("post_id", "media_key", name="uq_media_post_key"),
    )
    with op.batch_alter_table("media_items", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_media_items_creator_id"), ["creator_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_media_items_post_id"), ["post_id"], unique=False)
        batch_op.create_index("ix_media_retry", ["status", "next_retry_at"], unique=False)
        batch_op.create_index("ix_media_status", ["status"], unique=False)

    op.create_table(
        "download_jobs",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("media_item_id", sa.Integer(), nullable=False),
        sa.Column("post_id", sa.Integer(), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=False),
        sa.Column("status", sa.String(length=16), nullable=False),
        sa.Column("priority", sa.Integer(), nullable=False),
        sa.Column("attempt", sa.Integer(), nullable=False),
        sa.Column("progress_percent", sa.Float(), nullable=True),
        sa.Column("bytes_downloaded", sa.Integer(), nullable=True),
        sa.Column("total_bytes", sa.Integer(), nullable=True),
        sa.Column("speed_bps", sa.Integer(), nullable=True),
        sa.Column("eta_seconds", sa.Integer(), nullable=True),
        sa.Column("stage", sa.String(length=16), nullable=True),
        sa.Column("worker_id", sa.String(length=32), nullable=True),
        sa.Column("started_at", sa.DateTime(), nullable=True),
        sa.Column("finished_at", sa.DateTime(), nullable=True),
        sa.Column("error", sa.Text(), nullable=True),
        sa.Column("error_class", sa.String(length=64), nullable=True),
        sa.Column("created_at", sa.DateTime(), nullable=False),
        sa.Column("updated_at", sa.DateTime(), nullable=False),
        sa.ForeignKeyConstraint(["creator_id"], ["creators.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["media_item_id"], ["media_items.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("download_jobs", schema=None) as batch_op:
        batch_op.create_index(
            batch_op.f("ix_download_jobs_creator_id"), ["creator_id"], unique=False
        )
        batch_op.create_index(
            batch_op.f("ix_download_jobs_media_item_id"), ["media_item_id"], unique=False
        )
        batch_op.create_index(batch_op.f("ix_download_jobs_post_id"), ["post_id"], unique=False)
        batch_op.create_index(
            "ix_jobs_status_priority", ["status", "priority", "created_at"], unique=False
        )
        batch_op.create_index(
            "uq_job_active_media",
            ["media_item_id"],
            unique=True,
            sqlite_where=sa.text("status IN ('queued','running')"),
        )

    op.create_table(
        "history",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("occurred_at", sa.DateTime(), nullable=False),
        sa.Column("event_type", sa.String(length=32), nullable=False),
        sa.Column("level", sa.String(length=8), nullable=False),
        sa.Column("creator_id", sa.Integer(), nullable=True),
        sa.Column("post_id", sa.Integer(), nullable=True),
        sa.Column("media_item_id", sa.Integer(), nullable=True),
        sa.Column("message", sa.Text(), nullable=False),
        sa.Column("data", sa.JSON(), nullable=True),
        sa.ForeignKeyConstraint(["creator_id"], ["creators.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["media_item_id"], ["media_items.id"], ondelete="SET NULL"),
        sa.ForeignKeyConstraint(["post_id"], ["posts.id"], ondelete="SET NULL"),
        sa.PrimaryKeyConstraint("id"),
    )
    with op.batch_alter_table("history", schema=None) as batch_op:
        batch_op.create_index(batch_op.f("ix_history_creator_id"), ["creator_id"], unique=False)
        batch_op.create_index(batch_op.f("ix_history_event_type"), ["event_type"], unique=False)
        batch_op.create_index(batch_op.f("ix_history_occurred_at"), ["occurred_at"], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table("history", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_history_occurred_at"))
        batch_op.drop_index(batch_op.f("ix_history_event_type"))
        batch_op.drop_index(batch_op.f("ix_history_creator_id"))

    op.drop_table("history")
    with op.batch_alter_table("download_jobs", schema=None) as batch_op:
        batch_op.drop_index(
            "uq_job_active_media", sqlite_where=sa.text("status IN ('queued','running')")
        )
        batch_op.drop_index("ix_jobs_status_priority")
        batch_op.drop_index(batch_op.f("ix_download_jobs_post_id"))
        batch_op.drop_index(batch_op.f("ix_download_jobs_media_item_id"))
        batch_op.drop_index(batch_op.f("ix_download_jobs_creator_id"))

    op.drop_table("download_jobs")
    with op.batch_alter_table("media_items", schema=None) as batch_op:
        batch_op.drop_index("ix_media_status")
        batch_op.drop_index("ix_media_retry")
        batch_op.drop_index(batch_op.f("ix_media_items_post_id"))
        batch_op.drop_index(batch_op.f("ix_media_items_creator_id"))

    op.drop_table("media_items")
    with op.batch_alter_table("scan_runs", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_scan_runs_creator_id"))

    op.drop_table("scan_runs")
    with op.batch_alter_table("posts", schema=None) as batch_op:
        batch_op.drop_index(batch_op.f("ix_posts_status"))
        batch_op.drop_index(batch_op.f("ix_posts_published_at"))
        batch_op.drop_index("ix_posts_creator_published")
        batch_op.drop_index(batch_op.f("ix_posts_creator_id"))

    op.drop_table("posts")
    op.drop_table("system_state")
    op.drop_table("settings")
    op.drop_table("creators")
    # ### end Alembic commands ###
